WIP: Whittle down test suite

diff --git a/.github/workflows/testsuite.yml b/.github/workflows/testsuite.yml
--- a/.github/workflows/testsuite.yml
+++ b/.github/workflows/testsuite.yml
@@ -36,8 +36,8 @@ jobs:
     strategy:
       matrix:
         os:
-          - ubuntu
-          - macos
+          # - ubuntu
+          # - macos
           - windows
         python-version:
           # When changing this list, be sure to check the [gh] list in
@@ -45,14 +45,14 @@ jobs:
           # Available versions:
           # https://github.com/actions/python-versions/blob/main/versions-manifest.json
           # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#available-versions-of-python-and-pypy
-          - "3.8"
-          - "3.9"
+          # - "3.8"
+          # - "3.9"
           - "3.10"
           - "3.11"
           - "3.12"
-          - "pypy-3.8"
-          - "pypy-3.9"
-          - "pypy-3.10"
+          # - "pypy-3.8"
+          # - "pypy-3.9"
+          # - "pypy-3.10"
       fail-fast: false
 
     steps:
@@ -80,11 +80,11 @@ jobs:
         run: |
           python -m tox -- -rfsEX
 
-      - name: "Retry tox for ${{ matrix.python-version }}"
-        if: failure()
-        run: |
-          # `exit 1` makes sure that the job remains red with flaky runs
-          python -m tox -- -rfsEX --lf -vvvvv && exit 1
+      # - name: "Retry tox for ${{ matrix.python-version }}"
+      #   if: failure()
+      #   run: |
+      #     # `exit 1` makes sure that the job remains red with flaky runs
+      #     python -m tox -- -rfsEX --lf -vvvvv && exit 1
 
   # This job aggregates test results. It's the required check for branch protection.
   # https://github.com/marketplace/actions/alls-green#why
